### PR TITLE
[TUT] Meta Object - 10300

### PR DESCRIPTION
**Pull request by jpradocueva**
new pull request template

### CODE REVIEW

**Comment by jpradocueva** [comment]
@bsilverajan Bill this issue needs to be addressed by 16th of May or we will have to close the PR.

**Comment by bsilverajan** [comment]
> @bsilverajan Bill this issue needs to be addressed by 16th of May or we will have to close the PR.

@jpradocueva please find the rectified description field now in this following pull request:

#150

**Comment by jpradocueva** [comment]
The Object has passed validation and it is ready for WG review

**Comment by jpradocueva** [comment]
@bsilverajan the PR was accepted and merged into the TUT branch. The new revised object has passed validation and it is ready for Working Group review this coming Thursday.

**Comment by jpradocueva** [comment]
Due to problems with the DDF.xml (it was a very old file). I have create a new PR that contains this Object but with the correct DDF.xml.
This PR is superseded by PR #154

**Pull request closed without merging**
