### PR TITLE
Update of 3336.xml with lat/long in float

### PR DESCRIPTION
**Pull request by jaimejim**
Proposal update of 3336.xml with lat/long/uncert in float.
In relation to https://github.com/OpenMobileAlliance/lwm2m-registry/issues/257

new pull request template

### CODE REVIEW

**Comment by seanmcilroy29** [comment]
@jaimejim - could you push your PR into the dev branch

**Review by jpradocueva — CHANGES_REQUESTED** [review]
We will prepare a new branch for you in order to avoid future conflicts. 
https://github.com/OpenMobileAlliance/lwm2m-registry/issues/257#issuecomment-778268300

**Comment by seanmcilroy29** [comment]
New branch create for the update to Obj - 3336 See - https://github.com/OpenMobileAlliance/lwm2m-registry/tree/3336_update

**Comment by mkgillmore** [comment]
Pull request is on the wrong branch and has multiple problems.  The change for reusable resource "String Latitude" needs to be a new RR.

**Pull request closed without merging**
