### PR TITLE
[SE Water] Gas Readings - 10313 

### PR DESCRIPTION
**Pull request by aforster23**
Object updated with the following recommended changes:

•	Object version updated to 1.0
•	LwM2M version updated 1.0
•	Object ID updated to 10313
•	Object urn updated to urn:oma:lwm2m❌10313
•	The description in your submission is Object to periodically log readings from any gas sensor (eg H2S, VOCx, methane etc) but in the object the description is Periodic gas sensor measurements

[Gas_Readings (1).zip](https://github.com/OpenMobileAlliance/lwm2m-registry/files/3140247/Gas_Readings.1.zip)

new pull request template

### CODE REVIEW

**Comment by seanmcilroy29** [comment]
@aforster23 - The object has been added as zip file to the comments box and not submitted as a PR to the SE Water branch. 

What you need to do is;
1.	From here https://github.com/OpenMobileAlliance/lwm2m-registry/tree/SE-Water click ‘Upload files’
2.	Drag your object into the box that is displayed. Please note that your file needs to be named ‘10313’.
3.	To commit the changes add text to the highlighted yellow areas.
a.	Select ‘ Create a new branch for this commit and start a pull request’ and then click propose changes

image

Then add the following text and then click 'create pull request'
image

**Comment by aforster23** [comment]
Hi Sean, yes we tried this previously but when we go to the link in step 1 and click upload files we get a message saying Uploads are disabled. Can you grant this ‘pish access’?:

[cid:image003.jpg@01D503E6.16738AD0]

**Comment by aforster23** [comment]
FYI my git username is aforster23 if you need to add that to allow push…..

thanks

**Comment by seanmcilroy29** [comment]
Issue closed see #149

**Pull request closed without merging**
