### PR TITLE
Add object 10497 #772

### PR DESCRIPTION
**Pull request by workgreg**
> Note:

**In making a submission to the Open Mobile Alliance Registry, you understand and agree that your submission is made under the BSD-3 Clause License as set forth on the Open Mobile Alliance Registry and that additional formats of your submission may be created by the Open Mobile Alliance tools and processes, which may convert the content of your submission, and that the Open Mobile Alliance bears no liability for the additional formats of your submission nor for any conversion of the content of your submission.**

### CODE REVIEW

**Comment by jpradocueva** [comment]
## Failed Validation
@workgreg  the object failed validation. See details below. Let's know if you need assistance.

Error | Time | Description | ObjectID and/or ResourceID
-- | -- | -- | --
[406](https://guidelines.openmobilealliance.org/validation-code) |   | Object missing ending LF in the file | 10497 |  
[402](https://guidelines.openmobilealliance.org/validation-code) |   | Object Name miss match | 10497 |  
[50](https://guidelines.openmobilealliance.org/validation-code) |   | File missing in DDF.xml | version_history/10497-1_0.xml

**Comment by gocadimic** [comment]
@workgreg,
we noticed that the copyright license for object 10497 is dated 2019. We're not quite sure about the actual creation date of the object, though.

Can you clarify if the 2019 copyright year is correct or if it needs an update?

Thanks for looking into this!

**Comment by workgreg** [comment]
> @workgreg, we noticed that the copyright license for object 10497 is dated 2019. We're not quite sure about the actual creation date of the object, though.
> 
> Can you clarify if the 2019 copyright year is correct or if it needs an update?
> 
> Thanks for looking into this!

I copied the copyright notice from an old XML file. The copyright year should be 2024.

**Comment by gocadimic** [comment]
@workgreg,

The copyright year was updated to 2024 for the object 10497 and the other seven objects owned by SEW (10487-10493.xml), as all objects were created this year. 
Can you please confirm those changes?
Please see also PR #768

**Review by mkgillmore — APPROVED** [review]

**Pull request merged**
