### PR TITLE
Using numeric resource types for lat/lon/uncertainty for Object 3336

### PR DESCRIPTION
**Pull request by akeranen**

### CODE REVIEW

**Comment by akeranen** [comment]
Fixes #589

**Comment by jpradocueva** [comment]
@akeranen based on the changes applied to this object, the version should be probably marked as v2.0 rather than v1.1.
See https://www.md2html-tool.com/docs/OpenMobileAlliance/LwM2M/development/02313f6/TS_Core/OMA-TS-LightweightM2M_Core-V1_2-20201110-A_full.html#7-2-0-72-Object-Versioning

**Comment by akeranen** [comment]
Good catch @jpradocueva. Fixed now.

**Comment by mkgillmore** [comment]
Group agrees to merge 5/18/2021

**Pull request merged**
