### PR TITLE
[ADMIN] IPSO license update

### PR DESCRIPTION
**Pull request by seanmcilroy29**
IPSO license update

### CODE REVIEW

**Review by jpradocueva — CHANGES_REQUESTED** [review]
The name of the organization should be kept to IPSO.

**Comment by seanmcilroy29** [comment]
If IPSO has been dissolved as an Alliance to become a WG entity within OMA, shouldn't OMA be the over arching Copy right organisation?

**Comment by jpradocueva** [comment]
This is a tough call. My view is that the objects were created by IPSO. If we now change the name of the organization we are overwriting the original creator. I don't think that this is right. These objects were created outside of OMA.

**Comment by jmudge** [comment]
Does IPSO still exist as a legal entity now? My impression is that copyright can only be asserted by legal entities. (Note the copyright year is being updated to 2019.)

**Comment by seanmcilroy29** [comment]
I've created a PR to update these Objects with IPSO. 
When these Objects are submitted with the updated BSD license to ODM, IPSO will be highlighted as holding the Copyright, but is this correct?

**Pull request merged**
