### PR TITLE
[ATT] Update Resoure 9 of ObjectID 10308

### PR DESCRIPTION
**Pull request by jpradocueva**
This resource is mandatory, therefore a new version is needed.

new pull request template

### CODE REVIEW

**Review by Smees — APPROVED** [review]

**Comment by jpradocueva** [comment]
Resource 9 is mandatory and it has received the following changes:
* Name: from "CE Mode" to "CE_LEVEL"
* Type: from "String" to  "Integer"
* RangeEnumeration: from empty to 0,1,2
* New Description: 
From: "This resource indicates the CE Mode the IoT module is currently in. Potential values: Mode A, Mode B."
To: 
>"This resource indicates the Coverage Enhancement Level defined for LTE-M and NB-IoT. The Coverage Enhancement Level is on a range from 0-2. AT&T NB-IoT supports CE MODE A and B (CE LEVEL 0,1,2) and AT&T LTE-M supports CE MODE A (CE Level 0,1)."
* License: from MIT to BSD-3

**Review by seanmcilroy29 — APPROVED** [review]
Validates OK
Should ATT be updated to AT&T in the License header?
Also the ``All rights reserved.`` should be removed'
See PR #359 for an update to remove text

Also, the following statement has been added which differs from the other BSD-3 Licenses
``The above license is used as a license under copyright only. Please
reference the company patent licensing terms:
www.att.com``

**Review by jmudge — APPROVED** [review]
Have AT&T agreed the copyright statement?

**Comment by Smees** [comment]
Hi Sean –

I seem to recall there was some software problem with using the ‘&’ in the header.  In any case I think it’s fine using ATT instead of AT&T.

David

**Comment by mkgillmore** [comment]
Group agrees to merge 12/12/2019

**Pull request merged**
