### PR TITLE
[CloudMinds]10319-RCU Control

### PR DESCRIPTION
**Pull request by Kenny-SZ**
This LWM2M Object includes all operations on RCUs.

### CODE REVIEW

**Comment by seanmcilroy29** [comment]
@Kenny-SZ - No Object file submitted against this PR

**Comment by seanmcilroy29** [comment]
@Kenny-SZ - No Object file submitted against this PR

**Comment by seanmcilroy29** [comment]
@Kenny-SZ  - No Object File submitted against this PR

**Comment by Kenny-SZ** [comment]
> @Kenny-SZ - No Object file submitted against this PR

Uploaded.

**Comment by seanmcilroy29** [comment]
@Kenny-SZ - File now available for submission

**Pull request merged**
