### PR TITLE
[ADMIN] Aligning updates from Test to PROD

### PR DESCRIPTION
**Pull request by seanmcilroy29**
Aligning updates from Test to PROD

### CODE REVIEW

**Review by jmudge — CHANGES_REQUESTED** [review]
There are the following comments:

1. In DDF.xml the path http://www.openmobilealliance.org/release/LWM2M_VirtualObserveNotify/V1_0-20190711-A/OMA-TS-LWM2M_VirtualObserveNotify-V1_0-20190711-A.pdf should be corrected to http://www.openmobilealliance.org/release/LwM2M_VON/V1_0-20190711-A/OMA-TS-LWM2M_VirtualObserveNotify-V1_0-20190711-A.pdf

2. The contents of LWM2M_VirtualObserveNotify-v1_0.xml do not match that of the published file http://www.openmobilealliance.org/tech/profiles/LWM2M_VirtualObserveNotify-v1_0.xml . It is suggested that the contents of the registry file is corrected.

**Review by jpradocueva — CHANGES_REQUESTED** [review]
Before merging this PR the TS for Object 22 needs to be in place in order to ensure that the error that points to a missing TS disappears.
Also, there is another error in the validation with the new Object 3407, which is easy to resolve. The DDF cannot contain a "TBD"



270 |   | Incorrect DDF URL | 3407
-- | -- | -- | --
270 |   | Detailed Error | The remote server returned an error: (40
270 |   |   | 4) Not Found.
270 |   | URL | https://raw.githubusercontent.com/OpenMo
270 |   |   | bileAlliance/lwm2m-registry/test/TBC

**Comment by seanmcilroy29** [comment]
@jpradocueva - currently ```TBC``` is applied to objects 10312, 10313 and 10314 in PROD and they don't create any errors so there are some inconsistencies with the tool

**Review by jmudge — APPROVED** [review]

**Comment by jpradocueva** [comment]
@seanmcilroy29 let's discuss it. I did a quick check and unless I am mistaking the validation shows an error because the DDF element contains an incorrect value "TBD". On the other objects: 10312, 10313 and 10314 the DDF elements are empty. We need to put in place the process that captures theses issues before merging into "test".

**Comment by seanmcilroy29** [comment]
@jpradocueva - I miss read your comments. I assumed that TBC couldn't appear in the DDF, not the DDF element. A PR has been created to remove this and the DDF validates with no errors

**Review by jpradocueva — APPROVED** [review]
Ok, I am having internal issues and I cannot validate Object 22. Please make sure that it validates correctly.

**Comment by jpradocueva** [comment]
@seanmcilroy29 OK to merge. I have resolved my internal problems and the ObjectID 22 validates correctly.

**Pull request merged**
