### PR TITLE
Sew reserve placeholder

### LINKED ISSUE #761: Manhole level monitoring - object definitions.
### 1. Choose the type of registration: ###
  - [x] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [x] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [x] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 7 new objects
Name of SDO, Company or individual    | South East Water Corporation
Object Name (as defined in the .xml file) | Water Level Readings
Short Object description, to be used in the public registry (max 134 characters) | Periodic water level measurements.
Object Name (as defined in the .xml file) | Tilt Readings
Short Object description, to be used in the public registry (max 134 characters) | Periodic tilt measurements.
Object Name (as defined in the .xml file) | Water Level Alarm
Short Object description, to be used in the public registry (max 134 characters) | This alarm is raised when the water level in a tank, manhole, etc. exceeds the specified threshold.
Object Name (as defined in the .xml file) | Trend Readings
Short Object description, to be used in the public registry (max 134 characters) | Periodic trend (rate of change) measurements.
Object Name (as defined in the .xml file) | Tilt Alarm
Short Object description, to be used in the public registry (max 134 characters) | This alarm is raised when the tilt/inclination of the device exceeds the specified threshold.
Object Name (as defined in the .xml file) | Trend Alarm
Short Object description, to be used in the public registry (max 134 characters) | This alarm is raised when the trend (rate of change) of a sensor input exceeds a specified threshold.
Object Name (as defined in the .xml file) | Manhole
Short Object description, to be used in the public registry (max 134 characters) | This object provides site commissioning configuration for devices operating in a sewer manhole.

### PR DESCRIPTION
**Pull request by workgreg**
> Note:

**In making a submission to the Open Mobile Alliance Registry, you understand and agree that your submission is made under the BSD-3 Clause License as set forth on the Open Mobile Alliance Registry and that additional formats of your submission may be created by the Open Mobile Alliance tools and processes, which may convert the content of your submission, and that the Open Mobile Alliance bears no liability for the additional formats of your submission nor for any conversion of the content of your submission.**

### CODE REVIEW

**Comment by jpradocueva** [comment]
@workgreg, the PR fails validation. You need to add the ObjectID to the `DDF` element in the `DDF.xml`file, See image:
image
This must be done for each of the new Objects in the DDF file.

**Comment by workgreg** [comment]
I've committed a fix for the issue in the DDF file. Do I need to do anything else to prompt a review?

**Comment by jpradocueva** [comment]
@workgreg, the object has failed validation, see [details](https://github.com/OpenMobileAlliance/lwm2m-registry/pull/773#issuecomment-2213665040) on the PR.

**Comment by workgreg** [comment]
> @workgreg, the object has failed validation, see [details](https://github.com/OpenMobileAlliance/lwm2m-registry/pull/773#issuecomment-2213665040) on the PR.

That PR is for a different issue.

This issue failed validation due to an error in DDF.xml which is addressed by https://github.com/OpenMobileAlliance/lwm2m-registry/pull/768/commits/9324d2257e9dcf66faf26c13a5d6b87ba9341416

**Comment by gocadimic** [comment]
@workgreg,

This PR has failed validation for obj 10493:3 due to error 415: Invalid Mandatory value. See bellow.
Screenshot 2024-07-10 at 15 18 28
Screenshot 2024-07-10 at 15 25 10

**Comment by gocadimic** [comment]
@workgreg,

The PR still didn't pass validation for obj 10493:3 due to the same error 415: Invalid Mandatory value. 
If you change an object, please remember to copy the updated object to the `version_history` folder.

Screenshot 2024-07-11 at 16 10 37

**Comment by gocadimic** [comment]
@workgreg, @workgreg, 
This pull request has passed validation after updating the Mandatory field to `<Mandatory>Mandatory</Mandatory>`.
According to the LWM2M XML Schema - v1.0, there is a restriction that the Mandatory field should be either "Mandatory" or "Optional". Please refer to the image below.

Screenshot 2024-07-12 at 13 05 30

**Comment by workgreg** [comment]
My apologies, I've just updated the definition of two objects. This will require validation.

**Comment by gocadimic** [comment]
@workgreg,

OK, It passed validation.

**Comment by jpradocueva** [comment]
Agreed by the DMSO WG on the Aug 27 call.

**Pull request merged**
