### PR TITLE
Allow multiple instances of firmware update object (5)

### PR DESCRIPTION
**Pull request by SeppoTakalo**
This change would allow multiple instances of firmware update object
so devices with more than one component, would allow each to be updated
separately while each of then would still expose their version information
properly.

For example:

```
5/0/6 = "BOOTLOADER"
5/0/7 = "v1.7.0"

5/1/6 = "application"
5/1/7 = "<git hash or version>"

5/2/6 = "modem"
5/2/7 = "1.3.0"
```

This change requires very minimal software changes, while enabling
usable feature.

Change is proposed in Issue #615

### CODE REVIEW

**Comment by jpradocueva** [comment]
If the group accepts this PR, the DDF.xml needs to be updated as well as add a new object 5-1_2.xml to the "version_history" folder.

**Comment by SeppoTakalo** [comment]
I have updated the PR to contain those mentioned changes to DDF.xml and version_history directory.

**Comment by jpradocueva** [comment]
@SeppoTakalo the metadata also needs to be updated, e.g. the location of the file document in the FTP and the copyright. Please note that you are providing a PR directly to an Object that is internally developed by the Working Group in a private repository. The group will have to evaluate your changes and decide how to proceed. If they accept the changes as suggested, the group will have to apply these changes on their internal (private) repository.

**Comment by hannestschofenig** [comment]
Hi Seppo, 

we discussed your proposal at our weekly conference call and there are two main issues: First, we have a software management object, which extends the firmware update object by adding multiple instances. In some sense this is what you are probably looking for. Second, there are concerns that this update will introduce to interoperability issues. 

For this reason, the group recommends to use the software management object (see https://raw.githubusercontent.com/OpenMobileAlliance/lwm2m-registry/prod/9.xml and http://www.openmobilealliance.org/release/LWM2M_SWMGMT/V1_0_2-20210119-A/OMA-TS-LWM2M_SwMgmt-V1_0_2-20210119-A.pdf) instead. We noticed that there is an inconsistency between the published object and what is described in the spec. We are working on an update of the spec.

**Comment by SeppoTakalo** [comment]
Hi Hannes,

Thank you for your answer. As the proposal is not going to be accepted, I'll close this PR and the linked in issue.

I think we will be proceeding with Software Management object.

Few reasons why we originally tried to avoid using it are regarding the state transitions that place too strict requirements for the embedded device:
* Transition from DOWNLOADED to DELIVERED requires application to be able to verify the package. But if the package was, for example MCUBoot image, it will be verified on reboot phase. Also, if server is observing the state, this generates traffic when sending notifications of state changes.
* Uninstallation might not be possible on all scenarions. There is only one error code defined for it. I think this state transition should be optional.
* Activation - Deactivation cycle seems unnecessary for embedded devices. The resource however is mandatory.

**Pull request closed without merging**
