### PR TITLE
Autosen reserve placeholder

### PR DESCRIPTION
**Pull request by walzsi**
related to #765 
> Note:

**In making a submission to the Open Mobile Alliance Registry, you understand and agree that your submission is made under the BSD-3 Clause License as set forth on the Open Mobile Alliance Registry and that additional formats of your submission may be created by the Open Mobile Alliance tools and processes, which may convert the content of your submission, and that the Open Mobile Alliance bears no liability for the additional formats of your submission nor for any conversion of the content of your submission.**

### CODE REVIEW

**Comment by jpradocueva** [comment]
@walzsi, the Objects failed validation due to the incorrect URN inside the objects. The URN should have "x" rather than "ext". See comments below.
image

**Comment by walzsi** [comment]
@gocadimic Why was this PR closed? The incorrect URNs have been corrected

**Comment by gocadimic** [comment]
@walzsi, sorry I did it by mistake.

**Comment by walzsi** [comment]
@gocadimic @jpradocueva Is there anything missing from my side to merge the PR?

**Comment by gocadimic** [comment]
@walzsi,
Everything appears to be in order. You can either have the Group Chair merge it or handle it yourself.

**Pull request merged**
