### PR TITLE
Changing resource 4 data type to address issue #567

### PR DESCRIPTION
**Pull request by mojanm**
Changing resource 4 data type to float to address Issue #567

### CODE REVIEW

**Comment by jpradocueva** [comment]
We need to create a new object revision in "version_history".

**Comment by mojanm** [comment]
Who normally does this?

**Comment by seanmcilroy29** [comment]
@Mojan - The staff will take care of this issue

**Comment by mkgillmore** [comment]
Group agreed to merge on 2/9/2021

**Comment by jpradocueva** [comment]
In PR #581 it was added a new version (2.0) to the "version_history" folder.

**Pull request merged**
