### PR TITLE
Test with version history updated to change snapshots folder to version_history

### PR DESCRIPTION
**Pull request by mkgillmore**
new pull request template

### CODE REVIEW

**Comment by mkgillmore** [comment]
Group agrees 7/30/2020 to move forward with this pull request.

**Comment by mkgillmore** [comment]
Group agrees to move this PR into production 8/20/2020

**Comment by jpradocueva** [comment]
This PR contains major changes to the OMNA Registry.
* In the root of the repository, the Object filenames are changed to the ObjectID without version.
* A new folder is created, "version_history" which contain ALL the objects but the file name is the combination of the ObjectID + Object Version. In the case of Objects produced by OMA the filename also includes the Service Indicator or 3rd digit, e.g. V1.0.1.

**Review by jpradocueva — APPROVED** [review]
These changes passed validation.

**Pull request merged**
