### PR TITLE
[Admin] Object 3336 - Duplicate resource 5518 removed

### PR DESCRIPTION
**Pull request by seanmcilroy29**
Object 3336 - Duplicate resource 5518 removed - See issue https://github.com/OpenMobileAlliance/lwm2m-registry/issues/583

### CODE REVIEW

**Review by jpradocueva — CHANGES_REQUESTED** [review]
We need to do the same changes in 3336-v1_0 and 3336-v1_1.

**Comment by seanmcilroy29** [comment]
Version History updated;
3336-v1_0 doesn't have the duplicated RR
3336-v1_1 updated

Validated with no errors

**Comment by jpradocueva** [comment]
@seanmcilroy29 it makes me wonder how is possible in that case that the 3336 v1.1 had introduced a duplicate in the first place. Can we check the history and see if this is an isolated issue or a wide spread problem, may be introduced by the tool that creates objects for the "version_history"?

**Review by jpradocueva — APPROVED** [review]
Ok

**Pull request merged**
