### PR TITLE
[BUG] Add LWM2Version & ObjectVersion to IPSO Objects

### PR DESCRIPTION
**Pull request by jpradocueva**
The content of this PR was requested by IPSO to add missing elements to the IPSO Objects.

### CODE REVIEW

**Review by seanmcilroy29 — APPROVED** [review]
Validated OK with all the Error `800`'s removed from the non-OMA objects

**Review by jmudge — APPROVED** [review]
There is the very minor observation that when viewed in GitHub the indentation of the LWM2MVersion and ObjectVersion tags appears differently to the surrounding tags e.g. https://github.com/OpenMobileAlliance/lwm2m-registry/blob/Error800_sm/10245.xml

**Comment by jpradocueva** [comment]
@jmudge @seanmcilroy29 you can install an extension in Visual Code called XML Tools v2.5.1 from Josh Johnson, https://github.com/DotJoshJohnson/vscode-xml/wiki/xml-formatting this extension allows auto-formatting by a clicking 3 keys. It may be worthy to install it and running before submitting the PR.

**Comment by jpradocueva** [comment]
I have added a label to remind us that we need to add the missing elements to the objects inside of the "version_history".

**Pull request merged**
