### PR TITLE
[Admin] Approved TS version updates

### PR DESCRIPTION
**Pull request by seanmcilroy29**
DMSE - Approved TS version updated and URL updated to https://www.omaspecworks.org/

### CODE REVIEW

**Review by jpradocueva — CHANGES_REQUESTED** [review]
I fail to understand why the location has been changed to https://www.omaspecworks.org/

**Comment by jpradocueva** [comment]
From my point of view the link should point to: http://www.openmobilealliance.org/release/ as a generic link that can be added to the template.

**Comment by seanmcilroy29** [comment]
The updates are in line with the SUP template you updated https://github.com/OpenMobileAlliance/OMA_Document_Templates/blob/master/SUP/n.xml.. where the template specifies - https://www.omaspecworks.org/

I'm not aware that the generic link has ever been http://www.openmobilealliance.org/release/, I believe it's always been http://www.openmobilealliance.org.

I'll make the updates to these files, as you've proposed and then I'll update the TS templates

**Review by jpradocueva — APPROVED** [review]
Ready to merge.

**Pull request merged**
