### PR TITLE
[HuaXiang] 10309 

### PR DESCRIPTION
**Pull request by JiaDeng-Git**
new pull request template

### CODE REVIEW

**Comment by jpradocueva** [comment]
@dengjialean 
We need to resolve the following issues:
- [x] Is "ShareParkingLock" a replacement of "DeviceDataContainer"?
- [x] Software license is too restricted. By setting the copyright to Hua Xiang  all rights reserved, other companies won't be able to use this Object. Are you considering to have a more open software license?
- [x] Incorrect schema filename: LWM2M-v1_0.xsd, should be name LWM2M.xsd.
- [x] LwM2M schema is set to v1.0 but the "LWM2MVersion" of the protocol is set to "1.1". This is incorrect. You need to decide if this Object is release for version 1.0 or v1.1 of LwM2M protocol.
- [x] URN is set to urn:oma:lwm2m:x:10309:1.0, as this object is the first version (1.0), there is no need to add the Object version to the URN. Therefore, URN needs to be changed to: urn:oma:lwm2m:x:10309
- [x] Once the above issues are addressed, we will validate the Object

**Comment by JiaDeng-Git** [comment]
------------------ 原始邮件 ------------------
发件人: "Joaquin"<notifications@github.com>;
发送时间: 2019年2月28日(星期四) 晚上9:48
收件人: "OpenMobileAlliance/lwm2m-registry"<lwm2m-registry@noreply.github.com>;
抄送: "邓嘉"<280858922@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [OpenMobileAlliance/lwm2m-registry] [HuaXiang] 10309  (#76)




@dengjialean
 We need to resolve the following issues:
  
 Is "ShareParkingLock" a replacement of "DeviceDataContainer"?
 
 Software license is too restricted. By setting the copyright to Hua Xiang  all rights reserved, other companies won't be able to use this Object. Are you considering to have a more open software license?
 
 Incorrect schema filename: LWM2M-v1_0.xsd, should be name LWM2M.xsd.
 
 LwM2M schema is set to v1.0 but the "LWM2MVersion" of the protocol is set to "1.1". This is incorrect. You need to decide if this Object is release for version 1.0 or v1.1 of LwM2M protocol.
 
 URN is set to urn:oma:lwm2m10309:1.0, as this object is the first version (1.0), there is no need to add the Object version to the URN. Therefore, URN needs to be changed to: urn:oma:lwm2m10309
 
 Once the above issues are addressed, we will validate the Object
  
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.










Dear Joaquin,

I'm honored to receive your letter.

I have answered your question one by one.

Please check it on GitHub.

Tank you for your contribution,we beae it in mand.

Best wishes to you.

**Comment by ScottTaftPotter** [comment]
We advise you to use functionality from existing objects instead of creating a new object. For instance, please consider the following:
- Location (object number 6) for latitude and longitude
- Device (object number 3) for battery level
- Connectivity Monitoring (object number 4) for RSSI

**Comment by JiaDeng-Git** [comment]
> We advise you to use functionality from existing objects instead of creating a new object. For instance, please consider the following:
> 
> * Location (object number 6) for latitude and longitude
> * Device (object number 3) for battery level
> * Connectivity Monitoring (object number 4) for RSSI

**Comment by ScottTaftPotter** [comment]
Using the decomposition we recommended would have preferable, but given your urgency, we have made only minor edits. In the future we will provide better guidelines for best practices.

**Pull request merged**
