### PR TITLE
[ADMIN] Resolve issues with 10314

### PR DESCRIPTION
**Pull request by jpradocueva**
Incorrect URN
Mismatch of the Schema and LWM2MVersion element.

### CODE REVIEW

**Review by seanmcilroy29 — APPROVED** [review]

**Review by jmudge — COMMENTED** [review]
- The updates to Common.xml are not indicated in PR and so may not be incorporated into test branch.
- GitHub is displaying merge conflicts.

**Comment by jpradocueva** [comment]
@jmudge please add the changes to this PR

**Comment by jmudge** [comment]
PR https://github.com/OpenMobileAlliance/lwm2m-registry/pull/262 has been produced to resolve the issues with 10314.xml

**Comment by jpradocueva** [comment]
This PR has been superseded by #262

**Pull request closed without merging**
