### PR TITLE
[ADMIN] CloudMinds merged into Test

### PR DESCRIPTION
**Pull request by seanmcilroy29**
CloudMinds merged into Test

- [X] Validation 
- [x]  Object 10367 was originally submitted directly against the Test feature branch - https://github.com/OpenMobileAlliance/lwm2m-registry/pull/364 and was closed
- The submitter indicated this place holder will be used at a later date

### CODE REVIEW

**Comment by Kenny-SZ** [comment]
10367.xml is deprecated since 10367 has been registered by other companies. In addition, 10368.xml(SpringMotor) and 10369.xml(MCU) should be added, thanks.

**Comment by Kenny-SZ** [comment]
Please make sure the following two objects are submit as well, thanks.
10368.xml	[CloudMinds] 10368-SpringMotor	last month
10369.xml	[CloudMinds] 10369-MCU	last month

**Comment by seanmcilroy29** [comment]
Yes both objects have been approved and merged
10368.xml [CloudMinds] 10368-SpringMotor 
10369.xml [CloudMinds] 10369-MCU

**Comment by jpradocueva** [comment]
Objects 10319 and 10320 failed validation.
Also, Object 10320 contains extra information and it has incorrect tags on some places towards the end of the file.

**Comment by seanmcilroy29** [comment]
Bug removed
- [x] Object 10320 Submitter removed Line 1 
- [x] Object 10320 Submitter removed Comment Tags 
- [x] Validated with Editor - no additional errors
- [x] Validated as Well-formed

**Comment by seanmcilroy29** [comment]
- [x] Validated with Editor - no additional errors
- [x] Validated as Well-formed

**Pull request merged**
