### PR TITLE
[Admin] Updating Approval date and Version

### PR DESCRIPTION
**Pull request by seanmcilroy29**
Updating Approval date, DDF TS URL and Version

Passed validation with the exception of `Incorrect TS URL`, which will be cleared when the TS is uploaded

### CODE REVIEW

**Review by jmudge — APPROVED** [review]

**Review by jpradocueva — CHANGES_REQUESTED** [review]
@seanmcilroy29 same changes should be done in the Object 15-2_0.xml inside of the "version_history" folder.

**Comment by seanmcilroy29** [comment]
@jpradocueva - The version_history update for v2.0 I left to see if the staff could have access to Matt's tool and apply the update that way. 

I've applied the update manually, but I'll continue to make a request to Matt for staff access to the tool.

**Comment by seanmcilroy29** [comment]
TS Place holder added - Validates with no errors

**Review by jpradocueva — APPROVED** [review]
Ok to merge into "test_15" branch, but we have to wait for BoD Approval before moving it to "development" branch.

**Pull request merged**
