### PR TITLE
[ADMIN] Removal of Vorto links

### PR DESCRIPTION
**Pull request by seanmcilroy29**
Removal of Vorto links

### CODE REVIEW

**Review by jmudge — COMMENTED** [review]
There seem to be some Vorto links left for the OMA objects. Are those links going to be left?

**Comment by seanmcilroy29** [comment]
Vorto link removed

**Comment by jmudge** [comment]
Thanks for the updates

**Review by jpradocueva — APPROVED** [review]
The PR validates correctly, ready to merge into the feature branch.

**Pull request merged**
