### PR TITLE
[BUG] Smart quotes removed from DMSE Objects

### PR DESCRIPTION
**Pull request by seanmcilroy29**
PR addresses Smart Quote Errors identified by #541 in the following Objects:
- 1
- 11
- 12
- 13

Validated - Smart Quotes removed from highlighted Objects

### CODE REVIEW

**Review by jpradocueva — APPROVED** [review]
Ok, we will have to validate again as the validation tool is not working at the moment.

**Review by jmudge — APPROVED** [review]

**Comment by jpradocueva** [comment]
@seanmcilroy29 it is confirmed, object 10 had also problems with smart quotes in Resources 2 and 11, but the problem was rectified at one point. However, in the "dev" and "test" branch of the "lwm2m-registry" the old version of this object still contains smart quotes. This is the reason why depending which branch we are validating the problem is identified or not. Same problem with Object 27.

**Comment by seanmcilroy29** [comment]
@jpradocueva - Object 27 now has [PR#158](https://github.com/OpenMobileAlliance/objects-lwm2m/pull/158/files) to resolve the character bug in `objects-lwm2m repo` and this PR reflects that change. 
The validation of `seanmcilroy29-patch-2` feature branch indicates that all of the OMA Object errors have now been resolved.

**Comment by mkgillmore** [comment]
version_history folder objects also need to have the "smart" "quotes" removed.  Otherwise,  IPSO has no concerns

**Pull request merged**
