### PR TITLE
[Vaisala] Re-usable resource Measurement Quality Indicator (6042)

### PR DESCRIPTION
**Pull request by dirtyha**
Added new definition for measurement quality re-usable resource.

### CODE REVIEW

**Comment by akeranen** [comment]
Thank you for the update! Looks good to me.

**Comment by mkgillmore** [comment]
6/20/2019 Group agrees to rename the description to Measurement Quality Enumeration and create a new RR called Measurement Quality Percentage that is a range from 0-100

**Comment by mkgillmore** [comment]
Consider renaming to Measurement Quality Indicator and Measurement Quality Level

**Review by akeranen — APPROVED** [review]

**Comment by mkgillmore** [comment]
Approved per 9/19/19 meeting,  didn't delete the branch yet

**Pull request merged**
