### PR TITLE
[Admin] Revised common updates

### PR DESCRIPTION
**Pull request by seanmcilroy29**
Revised Common.xml file updates

### CODE REVIEW

**Comment by seanmcilroy29** [comment]
A large number of Error have been added due to the newly added Units and Enumerations

Error | Time | Description | ObjectID and/or ResourceID
-- | -- | -- | --
551 |   | Incorrect Unit value (ms) | 5503
551 |   | Incorrect Unit value (/100) | 5531
551 |   | Incorrect Unit value (/100) | 5536
551 |   | Incorrect Unit value (/100) | 5548
551 |   | Incorrect Unit value (deg) | 5705
551 |   | Incorrect Unit value (Wh) | 5805
551 |   | Incorrect Unit value (varh) | 5815
551 |   | Incorrect Unit value (min) | 5825
551 |   | Incorrect Unit value (/100) | 5827
551 |   | Incorrect Unit value (/100) | 5828
551 |   | Incorrect Unit value (/100) | 5851
551 |   | Incorrect Unit value (ms) | 5903
551 |   | Incorrect Unit value (ms) | 5904
510 |   | Incorrect Description | 6041
510 |   | Incorrect Description | 6043
510 |   | Incorrect Description | 6044
510 |   | Incorrect Description | 6045
510 |   | Incorrect Description | 6046
510 |   | Incorrect Description | 6047
510 |   | Incorrect Description | 6048
510 |   | Incorrect Description | 6049
417 |   | Incorrect Unit value (ms) | 2052:1
417 |   | Incorrect Unit value (ms) | 2052:2
417 |   | Incorrect Unit value (ms) | 2052:3
417 |   | Incorrect Unit value (ms) | 2052:4
417 |   | Incorrect Unit value (ms) | 2052:5
417 |   | Incorrect Unit value (ms) | 2053:6
417 |   | Incorrect Unit value (ms) | 2053:7
417 |   | Incorrect Unit value (ms) | 2053:8
417 |   | Incorrect Unit value (ms) | 2053:9
417 |   | Incorrect Unit value (ms) | 2055:1
417 |   | Incorrect Unit value (Byte) | 2055:2
417 |   | Incorrect Unit value (Byte) | 2056:1
417 |   | Incorrect Unit value (ms) | 2057:1
417 |   | Incorrect Unit value (ms) | 2057:2
417 |   | Incorrect Unit value (ms) | 2057:3
417 |   | Incorrect Unit value (ms) | 2057:4
417 |   | Incorrect Unit value (ms) | 3200:5503
463 |   | RangeEnumeration is different | 3200:5504
463 |   | RangeEnumeration is different | 3203:5650
417 |   | Incorrect Unit value (ms) | 3302:5903
417 |   | Incorrect Unit value (ms) | 3302:5904
417 |   | Incorrect Unit value (Wh) | 3305:5805
417 |   | Incorrect Unit value (varh) | 3305:5815
463 |   | RangeEnumeration is different | 3306:5851
464 |   | Units is different | 3306:5851
417 |   | Incorrect Unit value (min) | 3310:5825
463 |   | RangeEnumeration is different | 3310:5826
463 |   | RangeEnumeration is different | 3310:5827
464 |   | Units is different | 3310:5827
463 |   | RangeEnumeration is different | 3310:5828
464 |   | Units is different | 3310:5828
463 |   | RangeEnumeration is different | 3311:5851
464 |   | Units is different | 3311:5851
417 |   | Incorrect Unit value (Wh) | 3311:5805
463 |   | RangeEnumeration is different | 3312:5851
464 |   | Units is different | 3312:5851
417 |   | Incorrect Unit value (Wh) | 3312:5805
417 |   | Incorrect Unit value (degree) | 3314:5705
463 |   | RangeEnumeration is different | 3314:5705
464 |   | Units is different | 3314:5705
417 |   | Incorrect Unit value (degree) | 3332:5705
463 |   | RangeEnumeration is different | 3332:5705
464 |   | Units is different | 3332:5705
463 |   | RangeEnumeration is different | 3333:5507
417 |   | Incorrect Unit value (degree) | 3336:5705
463 |   | RangeEnumeration is different | 3336:5705
464 |   | Units is different | 3336:5705
463 |   | RangeEnumeration is different | 3337:5536
464 |   | Units is different | 3337:5536
463 |   | RangeEnumeration is different | 3338:5548
464 |   | Units is different | 3338:5548
463 |   | RangeEnumeration is different | 3339:5548
464 |   | Units is different | 3339:5548
463 |   | RangeEnumeration is different | 3340:5526
463 |   | RangeEnumeration is different | 3341:5548
464 |   | Units is different | 3341:5548
463 |   | RangeEnumeration is different | 3341:5531
464 |   | Units is different | 3341:5531
463 |   | RangeEnumeration is different | 3343:5548
464 |   | Units is different | 3343:5548
202 |   | Description is different for same Obj... | 3380
202 |   | Description is different for same Obj... | 3380
417 |   | Incorrect Unit value (Ws) | 3388:910
417 |   | Incorrect Unit value (ms) | 3388:505
417 |   | Incorrect Unit value (ms) | 3390:127
417 |   | Incorrect Unit value (ms) | 3390:128
417 |   | Incorrect Unit value (ms) | 3391:139
417 |   | Incorrect Unit value (ms) | 3391:140
417 |   | Incorrect Unit value (ms) | 3393:106
417 |   | Incorrect Unit value (ms) | 3393:108
417 |   | Incorrect Unit value (ms) | 3394:5903
417 |   | Incorrect Unit value (ms) | 3394:5904
417 |   | Incorrect Unit value (ms) | 3395:203
417 |   | Incorrect Unit value (ms) | 3395:204
417 |   | Incorrect Unit value (byte) | 3396:908
417 |   | Incorrect Unit value (ms) | 3396:102
417 |   | Incorrect Unit value (ms) | 3396:124
417 |   | Incorrect Unit value (Ws) | 3396:910
417 |   | Incorrect Unit value (h) | 3396:930
417 |   | Incorrect Unit value (ms) | 3397:102
417 |   | Incorrect Unit value (ms) | 3397:138
417 |   | Incorrect Unit value (Ws) | 3397:910
417 |   | Incorrect Unit value (h) | 3397:930
417 |   | Incorrect Unit value (ms) | 3399:102
417 |   | Incorrect Unit value (Ws) | 3399:910
417 |   | Incorrect Unit value (h) | 3399:930
417 |   | Incorrect Unit value (ms) | 3401:5503
417 |   | Incorrect Unit value (ms) | 3404:652
417 |   | Incorrect Unit value (kW) | 10242:6
417 |   | Incorrect Unit value (kvar) | 10242:7
417 |   | Incorrect Unit value (kvarL) | 10242:8
417 |   | Incorrect Unit value (kvarC) | 10242:9
417 |   | Incorrect Unit value (kVA) | 10242:10
417 |   | Incorrect Unit value (kW) | 10242:16
417 |   | Incorrect Unit value (kvar) | 10242:17
417 |   | Incorrect Unit value (kvarL) | 10242:18
417 |   | Incorrect Unit value (kvarC) | 10242:19
417 |   | Incorrect Unit value (kVA) | 10242:20
417 |   | Incorrect Unit value (kW) | 10242:26
417 |   | Incorrect Unit value (kvar) | 10242:27
417 |   | Incorrect Unit value (kvarL) | 10242:28
417 |   | Incorrect Unit value (kvarC) | 10242:29
417 |   | Incorrect Unit value (kVA) | 10242:30
417 |   | Incorrect Unit value (kW III) | 10242:34
417 |   | Incorrect Unit value (kvar III) | 10242:35
417 |   | Incorrect Unit value (kvarL III) | 10242:36
417 |   | Incorrect Unit value (kvarC III) | 10242:37
417 |   | Incorrect Unit value (kVA III) | 10242:38
417 |   | Incorrect Unit value (kW/h III) | 10242:41
417 |   | Incorrect Unit value (kvar/h III) | 10242:42
417 |   | Incorrect Unit value (kvarL/h III) | 10242:43
417 |   | Incorrect Unit value (kvarC/h III) | 10242:44
417 |   | Incorrect Unit value (kVA/h III) | 10242:45
417 |   | Incorrect Unit value (kW) | 10243:6
417 |   | Incorrect Unit value (kvar) | 10243:7
417 |   | Incorrect Unit value (kvarL) | 10243:8
417 |   | Incorrect Unit value (kvarC) | 10243:9
417 |   | Incorrect Unit value (kVA) | 10243:10
417 |   | Incorrect Unit value (kW/h) | 10243:14
417 |   | Incorrect Unit value (kvar/h) | 10243:15
417 |   | Incorrect Unit value (kVA/h) | 10243:16
417 |   | Incorrect Unit value (km/h) | 10244:1
417 |   | Incorrect Unit value (kW) | 10244:4
417 |   | Incorrect Unit value (Wh) | 10244:5
417 |   | Incorrect Unit value (Wh/km) | 10244:6
417 |   | Incorrect Unit value (km) | 10244:7
417 |   | Incorrect Unit value (minute) | 10244:12
417 |   | Incorrect Unit value (Ah) | 10244:15
417 |   | Incorrect Unit value (mV) | 10244:18
417 |   | Incorrect Unit value (mV) | 10244:19
417 |   | Incorrect Unit value (Celsius) | 10244:20
417 |   | Incorrect Unit value (Celsius) | 10244:21
417 |   | Incorrect Unit value (Celsius) | 10244:25
417 |   | Incorrect Unit value (rpm) | 10244:26
417 |   | Incorrect Unit value (Celsius) | 10244:27
417 |   | Incorrect Unit value (degrees) | 10245:2
417 |   | Incorrect Unit value (dBm) | 10245:11
417 |   | Incorrect Unit value (bytes) | 10249:6
417 |   | Incorrect Unit value (bytes) | 10249:7
417 |   | Incorrect Unit value (mA) | 10254:0
417 |   | Incorrect Unit value (Wh) | 10257:5805
417 |   | Incorrect Unit value (Celcius) | 10257:12
417 |   | Incorrect Unit value (Celcius) | 10257:13
417 |   | Incorrect Unit value (Celcius) | 10257:14
417 |   | Incorrect Unit value (Celcius) | 10257:15
417 |   | Incorrect Unit value (Kelvin) | 10257:16
417 |   | Incorrect Unit value (m^3 / s) | 10257:17
417 |   | Incorrect Unit value (m^3 / s) | 10257:18
417 |   | Incorrect Unit value (m^3) | 10257:20
417 |   | Incorrect Unit value (m^3) | 10257:21
417 |   | Incorrect Unit value (mA) | 10258:0
201 |   | Name is different for same Object ID | 10260
202 |   | Description is different for same Obj... | 10260
201 |   | Name is different for same Object ID | 10260
202 |   | Description is different for same Obj... | 10260
417 |   | Incorrect Unit value (Seconds) | 10266:6000
463 |   | RangeEnumeration is different | 10266:6000
464 |   | Units is different | 10266:6000
417 |   | Incorrect Unit value (Seconds) | 10266:6001
463 |   | RangeEnumeration is different | 10266:6001
464 |   | Units is different | 10266:6001
417 |   | Incorrect Unit value (Seconds) | 10267:6000
463 |   | RangeEnumeration is different | 10267:6000
464 |   | Units is different | 10267:6000
417 |   | Incorrect Unit value (Seconds) | 10267:6001
463 |   | RangeEnumeration is different | 10267:6001
464 |   | Units is different | 10267:6001
417 |   | Incorrect Unit value (Seconds) | 10268:6000
463 |   | RangeEnumeration is different | 10268:6000
464 |   | Units is different | 10268:6000
417 |   | Incorrect Unit value (Seconds) | 10268:6001
463 |   | RangeEnumeration is different | 10268:6001
464 |   | Units is different | 10268:6001
417 |   | Incorrect Unit value (Seconds) | 10269:6000
463 |   | RangeEnumeration is different | 10269:6000
464 |   | Units is different | 10269:6000
417 |   | Incorrect Unit value (Seconds) | 10269:6001
463 |   | RangeEnumeration is different | 10269:6001
464 |   | Units is different | 10269:6001
417 |   | Incorrect Unit value (Seconds) | 10270:6000
463 |   | RangeEnumeration is different | 10270:6000
464 |   | Units is different | 10270:6000
417 |   | Incorrect Unit value (Seconds) | 10270:6001
463 |   | RangeEnumeration is different | 10270:6001
464 |   | Units is different | 10270:6001
417 |   | Incorrect Unit value (Seconds) | 10271:6000
463 |   | RangeEnumeration is different | 10271:6000
464 |   | Units is different | 10271:6000
417 |   | Incorrect Unit value (Seconds) | 10271:6001
463 |   | RangeEnumeration is different | 10271:6001
464 |   | Units is different | 10271:6001
417 |   | Incorrect Unit value (Seconds) | 10272:6019
463 |   | RangeEnumeration is different | 10272:6019
464 |   | Units is different | 10272:6019
463 |   | RangeEnumeration is different | 10272:6024
417 |   | Incorrect Unit value (Seconds) | 10273:6019
463 |   | RangeEnumeration is different | 10273:6019
464 |   | Units is different | 10273:6019
463 |   | RangeEnumeration is different | 10273:6024
417 |   | Incorrect Unit value (Seconds) | 10274:6019
463 |   | RangeEnumeration is different | 10274:6019
464 |   | Units is different | 10274:6019
463 |   | RangeEnumeration is different | 10274:6024
417 |   | Incorrect Unit value (Seconds) | 10275:6019
463 |   | RangeEnumeration is different | 10275:6019
464 |   | Units is different | 10275:6019
463 |   | RangeEnumeration is different | 10275:6024
417 |   | Incorrect Unit value (Seconds) | 10276:6019
463 |   | RangeEnumeration is different | 10276:6019
464 |   | Units is different | 10276:6019
463 |   | RangeEnumeration is different | 10276:6024
417 |   | Incorrect Unit value (Seconds) | 10277:6019
463 |   | RangeEnumeration is different | 10277:6019
464 |   | Units is different | 10277:6019
463 |   | RangeEnumeration is different | 10277:6024
417 |   | Incorrect Unit value (Seconds) | 10278:6019
463 |   | RangeEnumeration is different | 10278:6019
464 |   | Units is different | 10278:6019
463 |   | RangeEnumeration is different | 10278:6024
417 |   | Incorrect Unit value (Seconds) | 10279:6019
463 |   | RangeEnumeration is different | 10279:6019
464 |   | Units is different | 10279:6019
463 |   | RangeEnumeration is different | 10279:6024
417 |   | Incorrect Unit value (Seconds) | 10280:6019
463 |   | RangeEnumeration is different | 10280:6019
464 |   | Units is different | 10280:6019
463 |   | RangeEnumeration is different | 10280:6024
417 |   | Incorrect Unit value (Seconds) | 10281:6019
463 |   | RangeEnumeration is different | 10281:6019
464 |   | Units is different | 10281:6019
463 |   | RangeEnumeration is different | 10281:6024
417 |   | Incorrect Unit value (Seconds) | 10282:6019
463 |   | RangeEnumeration is different | 10282:6019
464 |   | Units is different | 10282:6019
463 |   | RangeEnumeration is different | 10282:6024
417 |   | Incorrect Unit value (Seconds) | 10283:6019
463 |   | RangeEnumeration is different | 10283:6019
464 |   | Units is different | 10283:6019
463 |   | RangeEnumeration is different | 10283:6024
417 |   | Incorrect Unit value (Seconds) | 10284:6019
463 |   | RangeEnumeration is different | 10284:6019
464 |   | Units is different | 10284:6019
463 |   | RangeEnumeration is different | 10284:6024
417 |   | Incorrect Unit value (Seconds) | 10290:6000
463 |   | RangeEnumeration is different | 10290:6000
464 |   | Units is different | 10290:6000
417 |   | Incorrect Unit value (Seconds) | 10290:6001
463 |   | RangeEnumeration is different | 10290:6001
464 |   | Units is different | 10290:6001
417 |   | Incorrect Unit value (Seconds) | 10291:6000
463 |   | RangeEnumeration is different | 10291:6000
464 |   | Units is different | 10291:6000
417 |   | Incorrect Unit value (Seconds) | 10291:6001
463 |   | RangeEnumeration is different | 10291:6001
464 |   | Units is different | 10291:6001
417 |   | Incorrect Unit value (Seconds) | 10291:6040
463 |   | RangeEnumeration is different | 10291:6040
464 |   | Units is different | 10291:6040
417 |   | Incorrect Unit value (Seconds) | 10292:6000
463 |   | RangeEnumeration is different | 10292:6000
464 |   | Units is different | 10292:6000
417 |   | Incorrect Unit value (Seconds) | 10292:6001
463 |   | RangeEnumeration is different | 10292:6001
464 |   | Units is different | 10292:6001
417 |   | Incorrect Unit value (Seconds) | 10292:6040
463 |   | RangeEnumeration is different | 10292:6040
464 |   | Units is different | 10292:6040
417 |   | Incorrect Unit value (dBm) | 10309:4

**Comment by jpradocueva** [comment]
@seanmcilroy29 the question here is which of the above errors are due to the changes introduced by the PR, a lot of these errors are related to the fact that the units in SenML are not updated with the secondary table. We need to filter most of those issues and just identify errors introduced by the PR changes.

**Comment by seanmcilroy29** [comment]
**Resource/Unit Errors Introduced by PR- 50**

Error | Description | ResourceID | Comments
-- | -- | -- | --
463 | RangeEnumeration is different | 6000 | 9 resources updated with ```..```
463 | RangeEnumeration is different | 6001 | 9 resources updated with ```..```
463 | RangeEnumeration is different | 6019 | 13 resources updated with ```..```
463 | RangeEnumeration is different | 6024 | 13 resources updated with ```..```
551 | Incorrect Unit value (/100) | 5536 | 6 percentage updates with (/100)


**As a Note** - Errors to be rectified by [draft secondary units table.](https://tools.ietf.org/html/draft-ietf-core-senml-more-units-03#page-5)

Error | Description | Comments |
-- | -- | --
417 | Incorrect Unit value (ms) | 38 errors
417 | Incorrect Unit value (Wh) | 9 errors
417 | Incorrect Unit value (varh) | 2 errors
417 | Incorrect Unit value (h) | 3 errors
417 | Incorrect Unit value (kW) | 5 errors
417 | Incorrect Unit value (kvar) | 4 errors
417 | IIncorrect Unit value (dBm) | 2 errors

**Comment by seanmcilroy29** [comment]
**Object 3380** - In the Error code page, this element has been marked as **DISABLED** 

202 | Description is different for a different version of the same Object ID | 
-- | --

**Object 10260** - Both error codes have been marked as **DISABLED** in the Error code page

201 | Name is different for a different version of the same Object ID | 
-- | --
202 | Description is different for a different version of the same Object ID |

**Both objects have error codes related to elements that should have been disabled.**

**Pull request merged**
