### PR TITLE
[ADMIN] Version history update

### PR DESCRIPTION
**Pull request by seanmcilroy29**
Version history updated with;
- uCIFI, 
- Non-Core Objects - 8, 9, 15, and 16
- Non-OMA Objects - 2051, 2053, 10245, 10256 and 10309
- DDF - Object 3410 description updated to remove smart quotes

Validates with no errors

### CODE REVIEW

**Review by jmudge — COMMENTED** [review]
There are the following comments:

1. Please note some of the version_history directory files still contain smart quotes (e.g. 1-1_1.xml). Was this intentional?
2. In file DDF.xml the Description for ObjectID 3410 does not exactly match that in file 3410.xml . It is suggested that this is corrected.

**Comment by seanmcilroy29** [comment]
@jmudge - All the DMSE Object smart quote updates were applied against the latest version releases, so 1-1_2.xml will have the change but previous versions such as 1-1_1.xml won't

**Review by jmudge — APPROVED** [review]

**Comment by jpradocueva** [comment]
Failed validation, it cannot find the TS (wrong date)

We need to repoint the TS files inside of the DDF to the new folder and date.

Error | Time | Description | ObjectID and/or ResourceID
-- | -- | -- | --
310 |   | Incorrect TS URL | 0 |  
310 |   | Detailed Error | The remote server returned an error: (40 |  
310 |   |   | 4) Not Found. |  
310 |   | Incorrect TS URL | 1 |  
310 |   | Detailed Error | The remote server returned an error: (40 |  
310 |   |   | 4) Not Found. |  
310 |   | Incorrect TS URL | 2 |  
310 |   | Detailed Error | The remote server returned an error: (40 |  
310 |   |   | 4) Not Found. |  
310 |   | Incorrect TS URL | 3 |  
310 |   | Detailed Error | The remote server returned an error: (40 |  
310 |   |   | 4) Not Found. |  
310 |   | Incorrect TS URL | 4 |  
310 |   | Detailed Error | The remote server returned an error: (40 |  
310 |   |   | 4) Not Found. |  
310 |   | Incorrect TS URL | 5 |  
310 |   | Detailed Error | The remote server returned an error: (40 |  
310 |   |   | 4) Not Found. |  
310 |   | Incorrect TS URL | 21 |  
310 |   | Detailed Error | The remote server returned an error: (40 |  
310 |   |   | 4) Not Found. |  
310 |   | Incorrect TS URL | 23 |  
310 |   | Detailed Error | The remote server returned an error: (40 |  
310 |   |   | 4) Not Found. |  
310 |   | Incorrect TS URL | 24 |  
310 |   | Detailed Error | The remote server returned an error: (40 |  
310 |   |   | 4) Not Found. |  
310 |   | Incorrect TS URL | 25 |  
310 |   | Detailed Error | The remote server returned an error: (40 |  
310 |   |   | 4) Not Found. |  
310 |   | Incorrect TS URL | 26 |  
310 |   | Detailed Error | The remote server returned an error: (40 |  
310 |   |   | 4) Not Found. |  
310 |   | Incorrect TS URL | 27 |  
310 |   | Detailed Error | The remote server returned an error: (40 |  
310 |   |   | 4) Not Found.

**Review by jpradocueva — CHANGES_REQUESTED** [review]
We need to update the date in the TS URL

**Comment by jpradocueva** [comment]
Resolution https://github.com/OpenMobileAlliance/lwm2m-registry/pull/555

**Comment by jpradocueva** [comment]
Final validation is correct.

**Pull request merged**
